# Generated by Django 4.2.16 on 2024-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('pubDate', models.DateTimeField()),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('guid', models.CharField(max_length=100)),
            ],
        ),
    ]
